var postingDatas;
var commentDatas;
var FavoriteDatas;
var FavoriteView;
var scoreDatas;
var allScoreDatas;
var postingPreferenceDatas;
var formData=new FormData();
var editFormData = new FormData();
var count = 0;