var postingDatas;
var commentDatas;
var favoriteDatas;
var favoriteView;
var scoreDatas;
var allScoreDatas;
var postingPreferenceDatas;
var formData=new FormData();
var editFormData = new FormData();
var count = 0;